#!/bin/sh
# This script filters out date strings and file paths from the input stream
# and replaces them with a canonical string.

# $Id: FilterLog 1.15 2020/11/21 AFsp-v10r3 $

# Differences in the outputs of test scripts can be obscured by differences in
# dates and file paths.

# Example
#   % tFiltAudio | FilterLog > new.log
#   % diff new.log tFiltAudio.log

# Editing:
# - Remove the file paths up to a "/test/" component
# - Remove the file paths up to a "/audiofiles/" component
# - Same as above with Windows file separators
# - Remove dates of the form " 2015-03-18 12:34:59"   for 2010 - 2099
# - Earlier dates are not modified (such dates should not occur in temporary
#   files).
sed 's| /.*/test/| --path--/test/|;
     s| [^ ]*\\test\\| --path--/test/|;
     s| [^ ]*/audiofiles/| --path--/audiofiles/|;
     s| [^ ]*\\audiofiles\\| --path--/audiofiles/|;
s| 20[1-9][0-9][-/][ 0-1][0-9][-/][ 0-3][0-9] [ 0-2][0-9]:[ 0-5][0-9]:[ 0-5][0-9]| YYYY-MM-dd hh:mm:ss|'
